# Generated by Django 4.1.2 on 2022-12-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
