# Generated by Django 4.1.2 on 2022-12-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_operations_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='categorie',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.categories'),
        ),
    ]
