# Generated by Django 4.1.2 on 2022-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_operations_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='categorie',
            field=models.ForeignKey(on_delete=models.SET('unknown'), to='main.categories'),
        ),
    ]
