# Generated by Django 4.1.2 on 2022-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_categories_name_alter_operations_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='unknown', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
