# Generated by Django 4.1.2 on 2022-10-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=200)),
                ('memo', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
